# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created: Wed Apr 23 19:42:48 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(750, 500)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_search = QtGui.QWidget()
        self.tab_search.setObjectName("tab_search")
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_search)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_auto_dl = QtGui.QPushButton(self.tab_search)
        self.btn_auto_dl.setEnabled(False)
        self.btn_auto_dl.setObjectName("btn_auto_dl")
        self.gridLayout.addWidget(self.btn_auto_dl, 5, 1, 1, 1)
        self.line = QtGui.QFrame(self.tab_search)
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 3)
        self.btn_start = QtGui.QPushButton(self.tab_search)
        self.btn_start.setEnabled(False)
        self.btn_start.setObjectName("btn_start")
        self.gridLayout.addWidget(self.btn_start, 1, 2, 1, 1)
        self.file_list = QtGui.QTreeView(self.tab_search)
        self.file_list.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.file_list.setProperty("showDropIndicator", False)
        self.file_list.setAlternatingRowColors(True)
        self.file_list.setItemsExpandable(False)
        self.file_list.setSortingEnabled(True)
        self.file_list.setAnimated(True)
        self.file_list.setAllColumnsShowFocus(True)
        self.file_list.setExpandsOnDoubleClick(False)
        self.file_list.setObjectName("file_list")
        self.gridLayout.addWidget(self.file_list, 4, 0, 1, 3)
        self.status_label = QtGui.QLabel(self.tab_search)
        self.status_label.setObjectName("status_label")
        self.gridLayout.addWidget(self.status_label, 3, 0, 1, 3)
        self.btn_dl_sel = QtGui.QPushButton(self.tab_search)
        self.btn_dl_sel.setEnabled(False)
        self.btn_dl_sel.setObjectName("btn_dl_sel")
        self.gridLayout.addWidget(self.btn_dl_sel, 5, 2, 1, 1)
        self.overall_progress = QtGui.QProgressBar(self.tab_search)
        self.overall_progress.setProperty("value", 0)
        self.overall_progress.setObjectName("overall_progress")
        self.gridLayout.addWidget(self.overall_progress, 6, 0, 1, 3)
        self.btn_skip = QtGui.QPushButton(self.tab_search)
        self.btn_skip.setEnabled(False)
        self.btn_skip.setObjectName("btn_skip")
        self.gridLayout.addWidget(self.btn_skip, 5, 0, 1, 1)
        self.btn_add_folder = QtGui.QPushButton(self.tab_search)
        self.btn_add_folder.setObjectName("btn_add_folder")
        self.gridLayout.addWidget(self.btn_add_folder, 1, 0, 1, 1)
        self.btn_add_file = QtGui.QPushButton(self.tab_search)
        self.btn_add_file.setObjectName("btn_add_file")
        self.gridLayout.addWidget(self.btn_add_file, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab_search, "")
        self.tab_settings = QtGui.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.chk_auto_dl = QtGui.QCheckBox(self.tab_settings)
        self.chk_auto_dl.setObjectName("chk_auto_dl")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.chk_auto_dl)
        self.label_auto_download = QtGui.QLabel(self.tab_settings)
        font = QtGui.QFont()
        font.setFamily("Droid Sans")
        font.setItalic(False)
        font.setUnderline(False)
        self.label_auto_download.setFont(font)
        self.label_auto_download.setTextFormat(QtCore.Qt.AutoText)
        self.label_auto_download.setScaledContents(False)
        self.label_auto_download.setWordWrap(True)
        self.label_auto_download.setObjectName("label_auto_download")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_auto_download)
        self.chk_overwrite = QtGui.QCheckBox(self.tab_settings)
        self.chk_overwrite.setObjectName("chk_overwrite")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.chk_overwrite)
        self.label_overwrite = QtGui.QLabel(self.tab_settings)
        self.label_overwrite.setWordWrap(True)
        self.label_overwrite.setObjectName("label_overwrite")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_overwrite)
        self.label_lang_indicator = QtGui.QLabel(self.tab_settings)
        self.label_lang_indicator.setObjectName("label_lang_indicator")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_lang_indicator)
        self.cbo_language = QtGui.QComboBox(self.tab_settings)
        self.cbo_language.setObjectName("cbo_language")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.cbo_language)
        self.label_language = QtGui.QLabel(self.tab_settings)
        self.label_language.setWordWrap(True)
        self.label_language.setObjectName("label_language")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.label_language)
        self.label_formats_indicator = QtGui.QLabel(self.tab_settings)
        self.label_formats_indicator.setObjectName("label_formats_indicator")
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_formats_indicator)
        self.edt_formats = QtGui.QLineEdit(self.tab_settings)
        self.edt_formats.setObjectName("edt_formats")
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.edt_formats)
        self.label_formats = QtGui.QLabel(self.tab_settings)
        self.label_formats.setWordWrap(True)
        self.label_formats.setObjectName("label_formats")
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.label_formats)
        self.label_folder_indicator = QtGui.QLabel(self.tab_settings)
        self.label_folder_indicator.setObjectName("label_folder_indicator")
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_folder_indicator)
        self.edt_subfolder = QtGui.QLineEdit(self.tab_settings)
        self.edt_subfolder.setObjectName("edt_subfolder")
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.LabelRole, self.edt_subfolder)
        self.label_subfolder = QtGui.QLabel(self.tab_settings)
        self.label_subfolder.setWordWrap(True)
        self.label_subfolder.setObjectName("label_subfolder")
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.FieldRole, self.label_subfolder)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.line_2 = QtGui.QFrame(self.tab_settings)
        self.line_2.setFrameShadow(QtGui.QFrame.Raised)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_info = QtGui.QLabel(self.tab_settings)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_info.setFont(font)
        self.label_info.setWordWrap(True)
        self.label_info.setObjectName("label_info")
        self.verticalLayout.addWidget(self.label_info)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_save_conf = QtGui.QPushButton(self.tab_settings)
        self.btn_save_conf.setObjectName("btn_save_conf")
        self.horizontalLayout_2.addWidget(self.btn_save_conf)
        self.btn_reset_conf = QtGui.QPushButton(self.tab_settings)
        self.btn_reset_conf.setCheckable(False)
        self.btn_reset_conf.setFlat(False)
        self.btn_reset_conf.setObjectName("btn_reset_conf")
        self.horizontalLayout_2.addWidget(self.btn_reset_conf)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_settings, "")
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.btn_add_folder, self.btn_add_file)
        Dialog.setTabOrder(self.btn_add_file, self.btn_start)
        Dialog.setTabOrder(self.btn_start, self.btn_skip)
        Dialog.setTabOrder(self.btn_skip, self.btn_auto_dl)
        Dialog.setTabOrder(self.btn_auto_dl, self.btn_dl_sel)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "PySub GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_auto_dl.setText(QtGui.QApplication.translate("Dialog", "Auto Download", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_start.setText(QtGui.QApplication.translate("Dialog", "Start searching", None, QtGui.QApplication.UnicodeUTF8))
        self.status_label.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>List of video files:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_dl_sel.setText(QtGui.QApplication.translate("Dialog", "Download Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_skip.setText(QtGui.QApplication.translate("Dialog", "Skip", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add_folder.setText(QtGui.QApplication.translate("Dialog", "Add Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add_file.setText(QtGui.QApplication.translate("Dialog", "Add File(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_search), QtGui.QApplication.translate("Dialog", "Search Subtitles", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_auto_dl.setText(QtGui.QApplication.translate("Dialog", "Auto Download Subtitles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_auto_download.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" color:#787878;\">Skips asking you which subtitle to download for every file and will automatically picks best one it can find. </span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_overwrite.setText(QtGui.QApplication.translate("Dialog", "Overwrite Existing Subs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_overwrite.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" color:#787878;\">Overwrite subtitle if one already exists without prompting user</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_lang_indicator.setText(QtGui.QApplication.translate("Dialog", "Language:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_language.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" color:#787878;\">Language for which to search subtitles for</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_formats_indicator.setText(QtGui.QApplication.translate("Dialog", "Additional formats:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_formats.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" color:#787878;\">Additional file formats to consider valid video files when scanning files/folders. Comma separated. e.g. &quot;.avi,.mpg,.etc&quot;</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_folder_indicator.setText(QtGui.QApplication.translate("Dialog", "Save folder:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_subfolder.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" color:#787878;\">Folder relative to video file where to save subtitle to, if empty the subtitle will be saved in same directory as the original video file. </span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_info.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p align=\"center\">Settings are applied for this session only - just change the option you want, if you want to apply them to every session by default click the button below to save this configuration.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save_conf.setText(QtGui.QApplication.translate("Dialog", "Save settings as default", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_reset_conf.setText(QtGui.QApplication.translate("Dialog", "Reset settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings), QtGui.QApplication.translate("Dialog", "Settings", None, QtGui.QApplication.UnicodeUTF8))

