# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created: Sun Apr 20 14:29:08 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(687, 390)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.overwrite = QtGui.QCheckBox(Dialog)
        self.overwrite.setObjectName("overwrite")
        self.gridLayout.addWidget(self.overwrite, 2, 1, 1, 1)
        self.results = QtGui.QColumnView(Dialog)
        self.results.setObjectName("results")
        self.gridLayout.addWidget(self.results, 6, 0, 1, 3)
        self.skip = QtGui.QPushButton(Dialog)
        self.skip.setObjectName("skip")
        self.gridLayout.addWidget(self.skip, 7, 0, 1, 1)
        self.do_auto_download = QtGui.QPushButton(Dialog)
        self.do_auto_download.setObjectName("do_auto_download")
        self.gridLayout.addWidget(self.do_auto_download, 7, 1, 1, 1)
        self.overall_progress = QtGui.QProgressBar(Dialog)
        self.overall_progress.setProperty("value", 24)
        self.overall_progress.setObjectName("overall_progress")
        self.gridLayout.addWidget(self.overall_progress, 8, 0, 1, 3)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 3)
        self.add_file = QtGui.QPushButton(Dialog)
        self.add_file.setObjectName("add_file")
        self.gridLayout.addWidget(self.add_file, 1, 1, 1, 1)
        self.download_selected = QtGui.QPushButton(Dialog)
        self.download_selected.setObjectName("download_selected")
        self.gridLayout.addWidget(self.download_selected, 7, 2, 1, 1)
        self.add_folder = QtGui.QPushButton(Dialog)
        self.add_folder.setObjectName("add_folder")
        self.gridLayout.addWidget(self.add_folder, 1, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.auto_download = QtGui.QCheckBox(Dialog)
        self.auto_download.setObjectName("auto_download")
        self.gridLayout_2.addWidget(self.auto_download, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.status_label = QtGui.QLabel(Dialog)
        self.status_label.setObjectName("status_label")
        self.gridLayout.addWidget(self.status_label, 4, 0, 1, 3)
        self.start = QtGui.QPushButton(Dialog)
        self.start.setObjectName("start")
        self.gridLayout.addWidget(self.start, 1, 2, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.language_label = QtGui.QLabel(Dialog)
        self.language_label.setObjectName("language_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.language_label)
        self.language = QtGui.QComboBox(Dialog)
        self.language.setObjectName("language")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.language)
        self.gridLayout.addLayout(self.formLayout, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.start, QtCore.SIGNAL("clicked(bool)"), self.language.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.add_folder, self.add_file)
        Dialog.setTabOrder(self.add_file, self.auto_download)
        Dialog.setTabOrder(self.auto_download, self.overwrite)
        Dialog.setTabOrder(self.overwrite, self.language)
        Dialog.setTabOrder(self.language, self.start)
        Dialog.setTabOrder(self.start, self.results)
        Dialog.setTabOrder(self.results, self.skip)
        Dialog.setTabOrder(self.skip, self.do_auto_download)
        Dialog.setTabOrder(self.do_auto_download, self.download_selected)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "PySub GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.overwrite.setText(QtGui.QApplication.translate("Dialog", "Overwrite if subtitle exists", None, QtGui.QApplication.UnicodeUTF8))
        self.skip.setText(QtGui.QApplication.translate("Dialog", "Skip", None, QtGui.QApplication.UnicodeUTF8))
        self.do_auto_download.setText(QtGui.QApplication.translate("Dialog", "Auto Download", None, QtGui.QApplication.UnicodeUTF8))
        self.add_file.setText(QtGui.QApplication.translate("Dialog", "Add File", None, QtGui.QApplication.UnicodeUTF8))
        self.download_selected.setText(QtGui.QApplication.translate("Dialog", "Download Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.add_folder.setText(QtGui.QApplication.translate("Dialog", "Add Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.auto_download.setText(QtGui.QApplication.translate("Dialog", "Auto download all subtitles", None, QtGui.QApplication.UnicodeUTF8))
        self.status_label.setText(QtGui.QApplication.translate("Dialog", "List of added valid files:", None, QtGui.QApplication.UnicodeUTF8))
        self.start.setText(QtGui.QApplication.translate("Dialog", "Start searching", None, QtGui.QApplication.UnicodeUTF8))
        self.language_label.setText(QtGui.QApplication.translate("Dialog", "Language", None, QtGui.QApplication.UnicodeUTF8))

