# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created: Tue Apr 22 18:46:54 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(687, 390)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.overwrite = QtGui.QCheckBox(Dialog)
        self.overwrite.setObjectName("overwrite")
        self.gridLayout.addWidget(self.overwrite, 2, 1, 1, 1)
        self.btn_skip = QtGui.QPushButton(Dialog)
        self.btn_skip.setEnabled(False)
        self.btn_skip.setObjectName("btn_skip")
        self.gridLayout.addWidget(self.btn_skip, 6, 0, 1, 1)
        self.btn_auto_dl = QtGui.QPushButton(Dialog)
        self.btn_auto_dl.setEnabled(False)
        self.btn_auto_dl.setObjectName("btn_auto_dl")
        self.gridLayout.addWidget(self.btn_auto_dl, 6, 1, 1, 1)
        self.overall_progress = QtGui.QProgressBar(Dialog)
        self.overall_progress.setProperty("value", 0)
        self.overall_progress.setObjectName("overall_progress")
        self.gridLayout.addWidget(self.overall_progress, 7, 0, 1, 3)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 3)
        self.btn_add_file = QtGui.QPushButton(Dialog)
        self.btn_add_file.setObjectName("btn_add_file")
        self.gridLayout.addWidget(self.btn_add_file, 1, 1, 1, 1)
        self.btn_dl_sel = QtGui.QPushButton(Dialog)
        self.btn_dl_sel.setEnabled(False)
        self.btn_dl_sel.setObjectName("btn_dl_sel")
        self.gridLayout.addWidget(self.btn_dl_sel, 6, 2, 1, 1)
        self.btn_add_folder = QtGui.QPushButton(Dialog)
        self.btn_add_folder.setObjectName("btn_add_folder")
        self.gridLayout.addWidget(self.btn_add_folder, 1, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.auto_download = QtGui.QCheckBox(Dialog)
        self.auto_download.setObjectName("auto_download")
        self.gridLayout_2.addWidget(self.auto_download, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.status_label = QtGui.QLabel(Dialog)
        self.status_label.setObjectName("status_label")
        self.gridLayout.addWidget(self.status_label, 4, 0, 1, 3)
        self.btn_start = QtGui.QPushButton(Dialog)
        self.btn_start.setEnabled(False)
        self.btn_start.setObjectName("btn_start")
        self.gridLayout.addWidget(self.btn_start, 1, 2, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.language_label = QtGui.QLabel(Dialog)
        self.language_label.setObjectName("language_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.language_label)
        self.language = QtGui.QComboBox(Dialog)
        self.language.setObjectName("language")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.language)
        self.gridLayout.addLayout(self.formLayout, 2, 2, 1, 1)
        self.file_list = QtGui.QTreeView(Dialog)
        self.file_list.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.file_list.setProperty("showDropIndicator", False)
        self.file_list.setAlternatingRowColors(True)
        self.file_list.setItemsExpandable(False)
        self.file_list.setSortingEnabled(True)
        self.file_list.setAnimated(True)
        self.file_list.setAllColumnsShowFocus(True)
        self.file_list.setExpandsOnDoubleClick(False)
        self.file_list.setObjectName("file_list")
        self.gridLayout.addWidget(self.file_list, 5, 0, 1, 3)
        self.verticalLayout_2.addLayout(self.gridLayout)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.btn_start, QtCore.SIGNAL("clicked(bool)"), self.language.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.btn_add_folder, self.btn_add_file)
        Dialog.setTabOrder(self.btn_add_file, self.auto_download)
        Dialog.setTabOrder(self.auto_download, self.overwrite)
        Dialog.setTabOrder(self.overwrite, self.language)
        Dialog.setTabOrder(self.language, self.btn_start)
        Dialog.setTabOrder(self.btn_start, self.btn_skip)
        Dialog.setTabOrder(self.btn_skip, self.btn_auto_dl)
        Dialog.setTabOrder(self.btn_auto_dl, self.btn_dl_sel)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "PySub GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.overwrite.setText(QtGui.QApplication.translate("Dialog", "Overwrite if subtitle exists", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_skip.setText(QtGui.QApplication.translate("Dialog", "Skip", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_auto_dl.setText(QtGui.QApplication.translate("Dialog", "Auto Download", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add_file.setText(QtGui.QApplication.translate("Dialog", "Add File(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_dl_sel.setText(QtGui.QApplication.translate("Dialog", "Download Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add_folder.setText(QtGui.QApplication.translate("Dialog", "Add Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.auto_download.setText(QtGui.QApplication.translate("Dialog", "Auto download all subtitles", None, QtGui.QApplication.UnicodeUTF8))
        self.status_label.setText(QtGui.QApplication.translate("Dialog", "List of added valid files:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_start.setText(QtGui.QApplication.translate("Dialog", "Start searching", None, QtGui.QApplication.UnicodeUTF8))
        self.language_label.setText(QtGui.QApplication.translate("Dialog", "Language", None, QtGui.QApplication.UnicodeUTF8))

