# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created: Sun Sep  7 12:34:02 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(853, 543)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_search = QtGui.QWidget()
        self.tab_search.setObjectName("tab_search")
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_search)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_auto_dl = QtGui.QPushButton(self.tab_search)
        self.btn_auto_dl.setEnabled(False)
        self.btn_auto_dl.setText("")
        self.btn_auto_dl.setObjectName("btn_auto_dl")
        self.gridLayout.addWidget(self.btn_auto_dl, 5, 1, 1, 1)
        self.line = QtGui.QFrame(self.tab_search)
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 3)
        self.btn_start = QtGui.QPushButton(self.tab_search)
        self.btn_start.setEnabled(False)
        self.btn_start.setObjectName("btn_start")
        self.gridLayout.addWidget(self.btn_start, 1, 2, 1, 1)
        self.file_list = QtGui.QTreeView(self.tab_search)
        self.file_list.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.file_list.setProperty("showDropIndicator", False)
        self.file_list.setAlternatingRowColors(True)
        self.file_list.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.file_list.setItemsExpandable(False)
        self.file_list.setSortingEnabled(True)
        self.file_list.setAnimated(True)
        self.file_list.setAllColumnsShowFocus(True)
        self.file_list.setExpandsOnDoubleClick(False)
        self.file_list.setObjectName("file_list")
        self.gridLayout.addWidget(self.file_list, 4, 0, 1, 3)
        self.status_label = QtGui.QLabel(self.tab_search)
        font = QtGui.QFont()
        font.setItalic(True)
        self.status_label.setFont(font)
        self.status_label.setObjectName("status_label")
        self.gridLayout.addWidget(self.status_label, 3, 0, 1, 3)
        self.btn_dl_sel = QtGui.QPushButton(self.tab_search)
        self.btn_dl_sel.setEnabled(False)
        self.btn_dl_sel.setObjectName("btn_dl_sel")
        self.gridLayout.addWidget(self.btn_dl_sel, 5, 2, 1, 1)
        self.btn_skip = QtGui.QPushButton(self.tab_search)
        self.btn_skip.setEnabled(False)
        self.btn_skip.setText("")
        self.btn_skip.setObjectName("btn_skip")
        self.gridLayout.addWidget(self.btn_skip, 5, 0, 1, 1)
        self.btn_add_folder = QtGui.QPushButton(self.tab_search)
        self.btn_add_folder.setObjectName("btn_add_folder")
        self.gridLayout.addWidget(self.btn_add_folder, 1, 0, 1, 1)
        self.btn_add_file = QtGui.QPushButton(self.tab_search)
        self.btn_add_file.setObjectName("btn_add_file")
        self.gridLayout.addWidget(self.btn_add_file, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab_search, "")
        self.tab_settings = QtGui.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bx_settings = QtGui.QToolBox(self.tab_settings)
        self.bx_settings.setObjectName("bx_settings")
        self.pge_set_norm = QtGui.QWidget()
        self.pge_set_norm.setGeometry(QtCore.QRect(0, 0, 813, 369))
        self.pge_set_norm.setObjectName("pge_set_norm")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.pge_set_norm)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.layout_chkboxes = QtGui.QFormLayout()
        self.layout_chkboxes.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.layout_chkboxes.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.layout_chkboxes.setObjectName("layout_chkboxes")
        self.chk_auto_dl = QtGui.QCheckBox(self.pge_set_norm)
        self.chk_auto_dl.setObjectName("chk_auto_dl")
        self.layout_chkboxes.setWidget(1, QtGui.QFormLayout.LabelRole, self.chk_auto_dl)
        self.lbl_auto_dl = QtGui.QLabel(self.pge_set_norm)
        font = QtGui.QFont()
        font.setFamily("Droid Sans")
        font.setItalic(False)
        font.setUnderline(False)
        self.lbl_auto_dl.setFont(font)
        self.lbl_auto_dl.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_auto_dl.setScaledContents(False)
        self.lbl_auto_dl.setWordWrap(True)
        self.lbl_auto_dl.setObjectName("lbl_auto_dl")
        self.layout_chkboxes.setWidget(1, QtGui.QFormLayout.FieldRole, self.lbl_auto_dl)
        self.chk_overwrite = QtGui.QCheckBox(self.pge_set_norm)
        self.chk_overwrite.setObjectName("chk_overwrite")
        self.layout_chkboxes.setWidget(3, QtGui.QFormLayout.LabelRole, self.chk_overwrite)
        self.lbl_overwrite = QtGui.QLabel(self.pge_set_norm)
        self.lbl_overwrite.setWordWrap(True)
        self.lbl_overwrite.setObjectName("lbl_overwrite")
        self.layout_chkboxes.setWidget(3, QtGui.QFormLayout.FieldRole, self.lbl_overwrite)
        self.dl_folder_layout = QtGui.QHBoxLayout()
        self.dl_folder_layout.setObjectName("dl_folder_layout")
        self.lbl_save_folder = QtGui.QLabel(self.pge_set_norm)
        self.lbl_save_folder.setObjectName("lbl_save_folder")
        self.dl_folder_layout.addWidget(self.lbl_save_folder)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.dl_folder_layout.addItem(spacerItem)
        self.lne_save_folder = QtGui.QLineEdit(self.pge_set_norm)
        self.lne_save_folder.setObjectName("lne_save_folder")
        self.dl_folder_layout.addWidget(self.lne_save_folder)
        self.layout_chkboxes.setLayout(5, QtGui.QFormLayout.SpanningRole, self.dl_folder_layout)
        self.language_layout = QtGui.QHBoxLayout()
        self.language_layout.setObjectName("language_layout")
        self.lbl_language = QtGui.QLabel(self.pge_set_norm)
        self.lbl_language.setWordWrap(True)
        self.lbl_language.setObjectName("lbl_language")
        self.language_layout.addWidget(self.lbl_language)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.language_layout.addItem(spacerItem1)
        self.cbo_language = QtGui.QComboBox(self.pge_set_norm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbo_language.sizePolicy().hasHeightForWidth())
        self.cbo_language.setSizePolicy(sizePolicy)
        self.cbo_language.setMinimumSize(QtCore.QSize(150, 0))
        self.cbo_language.setObjectName("cbo_language")
        self.language_layout.addWidget(self.cbo_language)
        self.layout_chkboxes.setLayout(6, QtGui.QFormLayout.SpanningRole, self.language_layout)
        self.lbl_prompt = QtGui.QLabel(self.pge_set_norm)
        self.lbl_prompt.setWordWrap(True)
        self.lbl_prompt.setObjectName("lbl_prompt")
        self.layout_chkboxes.setWidget(4, QtGui.QFormLayout.FieldRole, self.lbl_prompt)
        self.chk_prompt = QtGui.QCheckBox(self.pge_set_norm)
        self.chk_prompt.setObjectName("chk_prompt")
        self.layout_chkboxes.setWidget(4, QtGui.QFormLayout.LabelRole, self.chk_prompt)
        self.horizontalLayout_2.addLayout(self.layout_chkboxes)
        self.bx_settings.addItem(self.pge_set_norm, "")
        self.pge_set_adv = QtGui.QWidget()
        self.pge_set_adv.setGeometry(QtCore.QRect(0, 0, 760, 477))
        self.pge_set_adv.setObjectName("pge_set_adv")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pge_set_adv)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.advanced_group_box = QtGui.QGroupBox(self.pge_set_adv)
        self.advanced_group_box.setEnabled(False)
        self.advanced_group_box.setTitle("")
        self.advanced_group_box.setFlat(True)
        self.advanced_group_box.setCheckable(False)
        self.advanced_group_box.setChecked(False)
        self.advanced_group_box.setObjectName("advanced_group_box")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.advanced_group_box)
        self.horizontalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.advanced_layout = QtGui.QVBoxLayout()
        self.advanced_layout.setObjectName("advanced_layout")
        self.lbl_file_ext = QtGui.QLabel(self.advanced_group_box)
        self.lbl_file_ext.setObjectName("lbl_file_ext")
        self.advanced_layout.addWidget(self.lbl_file_ext)
        self.txt_file_ext = QtGui.QPlainTextEdit(self.advanced_group_box)
        self.txt_file_ext.setMinimumSize(QtCore.QSize(0, 0))
        self.txt_file_ext.setObjectName("txt_file_ext")
        self.advanced_layout.addWidget(self.txt_file_ext)
        self.lbl_sub_ext = QtGui.QLabel(self.advanced_group_box)
        self.lbl_sub_ext.setObjectName("lbl_sub_ext")
        self.advanced_layout.addWidget(self.lbl_sub_ext)
        self.txt_sub_ext = QtGui.QPlainTextEdit(self.advanced_group_box)
        self.txt_sub_ext.setObjectName("txt_sub_ext")
        self.advanced_layout.addWidget(self.txt_sub_ext)
        self.lbl_lang_json = QtGui.QLabel(self.advanced_group_box)
        self.lbl_lang_json.setObjectName("lbl_lang_json")
        self.advanced_layout.addWidget(self.lbl_lang_json)
        self.txt_lang_json = QtGui.QPlainTextEdit(self.advanced_group_box)
        self.txt_lang_json.setObjectName("txt_lang_json")
        self.advanced_layout.addWidget(self.txt_lang_json)
        self.cutoff_layout = QtGui.QHBoxLayout()
        self.cutoff_layout.setObjectName("cutoff_layout")
        self.lbl_cutoff = QtGui.QLabel(self.advanced_group_box)
        self.lbl_cutoff.setObjectName("lbl_cutoff")
        self.cutoff_layout.addWidget(self.lbl_cutoff)
        self.sl_cutoff = QtGui.QSlider(self.advanced_group_box)
        self.sl_cutoff.setMaximum(100)
        self.sl_cutoff.setSingleStep(1)
        self.sl_cutoff.setPageStep(1)
        self.sl_cutoff.setProperty("value", 75)
        self.sl_cutoff.setOrientation(QtCore.Qt.Horizontal)
        self.sl_cutoff.setInvertedAppearance(False)
        self.sl_cutoff.setInvertedControls(False)
        self.sl_cutoff.setObjectName("sl_cutoff")
        self.cutoff_layout.addWidget(self.sl_cutoff)
        self.sl_label = QtGui.QLabel(self.advanced_group_box)
        self.sl_label.setObjectName("sl_label")
        self.cutoff_layout.addWidget(self.sl_label)
        self.advanced_layout.addLayout(self.cutoff_layout)
        self.ua_server_layout = QtGui.QHBoxLayout()
        self.ua_server_layout.setObjectName("ua_server_layout")
        self.lbl_ua = QtGui.QLabel(self.advanced_group_box)
        self.lbl_ua.setObjectName("lbl_ua")
        self.ua_server_layout.addWidget(self.lbl_ua)
        self.lne_ua = QtGui.QLineEdit(self.advanced_group_box)
        self.lne_ua.setObjectName("lne_ua")
        self.ua_server_layout.addWidget(self.lne_ua)
        self.lbl_server = QtGui.QLabel(self.advanced_group_box)
        self.lbl_server.setObjectName("lbl_server")
        self.ua_server_layout.addWidget(self.lbl_server)
        self.lne_server = QtGui.QLineEdit(self.advanced_group_box)
        self.lne_server.setObjectName("lne_server")
        self.ua_server_layout.addWidget(self.lne_server)
        self.advanced_layout.addLayout(self.ua_server_layout)
        self.horizontalLayout_7.addLayout(self.advanced_layout)
        self.verticalLayout_3.addWidget(self.advanced_group_box)
        self.chk_enable_advanced_sett = QtGui.QCheckBox(self.pge_set_adv)
        self.chk_enable_advanced_sett.setObjectName("chk_enable_advanced_sett")
        self.verticalLayout_3.addWidget(self.chk_enable_advanced_sett)
        self.bx_settings.addItem(self.pge_set_adv, "")
        self.verticalLayout.addWidget(self.bx_settings)
        self.line_buttons = QtGui.QFrame(self.tab_settings)
        self.line_buttons.setFrameShadow(QtGui.QFrame.Raised)
        self.line_buttons.setFrameShape(QtGui.QFrame.HLine)
        self.line_buttons.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_buttons.setObjectName("line_buttons")
        self.verticalLayout.addWidget(self.line_buttons)
        self.layout_settings_buttons = QtGui.QHBoxLayout()
        self.layout_settings_buttons.setObjectName("layout_settings_buttons")
        self.btn_reset_conf = QtGui.QPushButton(self.tab_settings)
        self.btn_reset_conf.setCheckable(False)
        self.btn_reset_conf.setFlat(False)
        self.btn_reset_conf.setObjectName("btn_reset_conf")
        self.layout_settings_buttons.addWidget(self.btn_reset_conf)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_settings_buttons.addItem(spacerItem2)
        self.btn_save_conf = QtGui.QPushButton(self.tab_settings)
        self.btn_save_conf.setObjectName("btn_save_conf")
        self.layout_settings_buttons.addWidget(self.btn_save_conf)
        self.verticalLayout.addLayout(self.layout_settings_buttons)
        self.tabWidget.addTab(self.tab_settings, "")
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.bx_settings.setCurrentIndex(0)
        QtCore.QObject.connect(self.chk_enable_advanced_sett, QtCore.SIGNAL("toggled(bool)"), self.advanced_group_box.setEnabled)
        QtCore.QObject.connect(self.sl_cutoff, QtCore.SIGNAL("valueChanged(int)"), self.sl_label.setNum)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.btn_add_folder, self.btn_add_file)
        Dialog.setTabOrder(self.btn_add_file, self.btn_start)
        Dialog.setTabOrder(self.btn_start, self.btn_skip)
        Dialog.setTabOrder(self.btn_skip, self.btn_auto_dl)
        Dialog.setTabOrder(self.btn_auto_dl, self.btn_dl_sel)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "PySub GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_start.setText(QtGui.QApplication.translate("Dialog", "Start searching", None, QtGui.QApplication.UnicodeUTF8))
        self.status_label.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>List of video files:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_dl_sel.setText(QtGui.QApplication.translate("Dialog", "Download Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add_folder.setText(QtGui.QApplication.translate("Dialog", "Add Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add_file.setText(QtGui.QApplication.translate("Dialog", "Add File(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_search), QtGui.QApplication.translate("Dialog", "Search Subtitles", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_auto_dl.setText(QtGui.QApplication.translate("Dialog", "Auto Download Subtitles", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_auto_dl.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" color:#747474;\">Skips asking you which subtitle to download for every file and will automatically picks best one it can find. </span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_overwrite.setText(QtGui.QApplication.translate("Dialog", "Overwrite Existing Subs", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_overwrite.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" color:#747474;\">Overwrite subtitle if one already exists without prompting user</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_save_folder.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" color:#676767;\">Relative to video subtitle folder to save to:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_language.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" color:#737373;\">Search subtitles for this language:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_prompt.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" color:#747474;\">If auto download is used and it doesn\'t find any suitable subtitles you\'ll have to manually select one (or skip file)</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_prompt.setText(QtGui.QApplication.translate("Dialog", "Prompt if auto-dl fails", None, QtGui.QApplication.UnicodeUTF8))
        self.bx_settings.setItemText(self.bx_settings.indexOf(self.pge_set_norm), QtGui.QApplication.translate("Dialog", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_file_ext.setText(QtGui.QApplication.translate("Dialog", "File extensions", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_sub_ext.setText(QtGui.QApplication.translate("Dialog", "Sub ext", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_lang_json.setText(QtGui.QApplication.translate("Dialog", "Languages JSON:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_cutoff.setText(QtGui.QApplication.translate("Dialog", "Match cutoff:", None, QtGui.QApplication.UnicodeUTF8))
        self.sl_label.setText(QtGui.QApplication.translate("Dialog", "00", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_ua.setText(QtGui.QApplication.translate("Dialog", "User Agent:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_server.setText(QtGui.QApplication.translate("Dialog", "XMLRPC Server URL:", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_enable_advanced_sett.setText(QtGui.QApplication.translate("Dialog", "Enable Advanced Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.bx_settings.setItemText(self.bx_settings.indexOf(self.pge_set_adv), QtGui.QApplication.translate("Dialog", "Advanced Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_reset_conf.setText(QtGui.QApplication.translate("Dialog", "Reset to default", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save_conf.setText(QtGui.QApplication.translate("Dialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings), QtGui.QApplication.translate("Dialog", "Settings", None, QtGui.QApplication.UnicodeUTF8))

